return {
	White = Color3.fromRGB(255, 255, 255),
	Black = Color3.fromRGB(0, 0, 0),

	LightColor = Color3.fromRGB(255, 251, 233),
	DarkColor = Color3.fromRGB(46, 46, 46),
	ActiveColor = Color3.fromRGB(37, 150, 255),

	Orange = Color3.fromRGB(221, 115, 73),
	Cyan = Color3.fromRGB(67, 151, 155),
	Blue = Color3.fromRGB(131, 154, 255),
	Grey = Color3.fromRGB(103, 103, 103),
	Pink = Color3.fromRGB(235, 152, 170),
	Green = Color3.fromRGB(144, 201, 144),
	Lavender = Color3.fromRGB(178, 161, 226),
	Yellow = Color3.fromRGB(243, 222, 138),

	PersonIcon = "rbxassetid://92880718993502",
	ErrorIcon = "rbxassetid://125296846031995",
	QRIcon = "rbxassetid://88810305487005",
	SpinIcon = "rbxassetid://133829503098403",
	ExpandIcon = "rbxassetid://94477738676258",
	ThumbsUpIcon = "rbxassetid://123253224859029",
	ArrowIcon = "rbxassetid://87511818594750",
	DumbellIcon = "rbxassetid://117668867747255",
	KeyIcon = "rbxassetid://82703103936950",

	Font = {
		Base = Font.fromName("Ubuntu", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
		Italic = Font.fromName("Ubuntu", Enum.FontWeight.Regular, Enum.FontStyle.Italic),
		Bold = Font.fromName("Ubuntu", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
		ItalicBold = Font.fromName("Ubuntu", Enum.FontWeight.Bold, Enum.FontStyle.Italic),

		Title = Font.fromName("FredokaOne", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
	},
}
